/* ========================================================================
 * Bootstrap: transition.js v3.3.2
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */
+function(t){"use strict";function n(){var t=document.createElement("bootstrap"),n={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"};for(var e in n)if(void 0!==t.style[e])return{end:n[e]};return!1}t.fn.emulateTransitionEnd=function(n){var e=!1,r=this;t(this).one("bsTransitionEnd",function(){e=!0});var o=function(){e||t(r).trigger(t.support.transition.end)};return setTimeout(o,n),this},t(function(){t.support.transition=n(),t.support.transition&&(t.event.special.bsTransitionEnd={bindType:t.support.transition.end,delegateType:t.support.transition.end,handle:function(n){return t(n.target).is(this)?n.handleObj.handler.apply(this,arguments):void 0}})})}(jQuery),/* ========================================================================
 * Bootstrap: dropdown.js v3.3.2
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */
+function(t){"use strict";function n(n){n&&3===n.which||(t(o).remove(),t(i).each(function(){var r=t(this),o=e(r),i={relatedTarget:this};o.hasClass("open")&&(o.trigger(n=t.Event("hide.bs.dropdown",i)),n.isDefaultPrevented()||(r.attr("aria-expanded","false"),o.removeClass("open").trigger("hidden.bs.dropdown",i)))}))}function e(n){var e=n.attr("data-target");e||(e=n.attr("href"),e=e&&/#[A-Za-z]/.test(e)&&e.replace(/.*(?=#[^\s]*$)/,""));var r=e&&t(e);return r&&r.length?r:n.parent()}function r(n){return this.each(function(){var e=t(this),r=e.data("bs.dropdown");r||e.data("bs.dropdown",r=new a(this)),"string"==typeof n&&r[n].call(e)})}var o=".dropdown-backdrop",i='[data-toggle="dropdown"]',a=function(n){t(n).on("click.bs.dropdown",this.toggle)};a.VERSION="3.3.2",a.prototype.toggle=function(r){var o=t(this);if(!o.is(".disabled, :disabled")){var i=e(o),a=i.hasClass("open");if(n(),!a){"ontouchstart"in document.documentElement&&!i.closest(".navbar-nav").length&&t('<div class="dropdown-backdrop"/>').insertAfter(t(this)).on("click",n);var s={relatedTarget:this};if(i.trigger(r=t.Event("show.bs.dropdown",s)),r.isDefaultPrevented())return;o.trigger("focus").attr("aria-expanded","true"),i.toggleClass("open").trigger("shown.bs.dropdown",s)}return!1}},a.prototype.keydown=function(n){if(/(38|40|27|32)/.test(n.which)&&!/input|textarea/i.test(n.target.tagName)){var r=t(this);if(n.preventDefault(),n.stopPropagation(),!r.is(".disabled, :disabled")){var o=e(r),a=o.hasClass("open");if(!a&&27!=n.which||a&&27==n.which)return 27==n.which&&o.find(i).trigger("focus"),r.trigger("click");var s=" li:not(.divider):visible a",d=o.find('[role="menu"]'+s+', [role="listbox"]'+s);if(d.length){var c=d.index(n.target);38==n.which&&c>0&&c--,40==n.which&&c<d.length-1&&c++,~c||(c=0),d.eq(c).trigger("focus")}}}};var s=t.fn.dropdown;t.fn.dropdown=r,t.fn.dropdown.Constructor=a,t.fn.dropdown.noConflict=function(){return t.fn.dropdown=s,this},t(document).on("click.bs.dropdown.data-api",n).on("click.bs.dropdown.data-api",".dropdown form",function(t){t.stopPropagation()}).on("click.bs.dropdown.data-api",i,a.prototype.toggle).on("keydown.bs.dropdown.data-api",i,a.prototype.keydown).on("keydown.bs.dropdown.data-api",'[role="menu"]',a.prototype.keydown).on("keydown.bs.dropdown.data-api",'[role="listbox"]',a.prototype.keydown)}(jQuery),/* ========================================================================
 * Bootstrap: alert.js v3.3.2
 * http://getbootstrap.com/javascript/#alerts
 * ========================================================================
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */
+function(t){"use strict";function n(n){return this.each(function(){var e=t(this),o=e.data("bs.alert");o||e.data("bs.alert",o=new r(this)),"string"==typeof n&&o[n].call(e)})}var e='[data-dismiss="alert"]',r=function(n){t(n).on("click",e,this.close)};r.VERSION="3.3.2",r.TRANSITION_DURATION=150,r.prototype.close=function(n){function e(){a.detach().trigger("closed.bs.alert").remove()}var o=t(this),i=o.attr("data-target");i||(i=o.attr("href"),i=i&&i.replace(/.*(?=#[^\s]*$)/,""));var a=t(i);n&&n.preventDefault(),a.length||(a=o.closest(".alert")),a.trigger(n=t.Event("close.bs.alert")),n.isDefaultPrevented()||(a.removeClass("in"),t.support.transition&&a.hasClass("fade")?a.one("bsTransitionEnd",e).emulateTransitionEnd(r.TRANSITION_DURATION):e())};var o=t.fn.alert;t.fn.alert=n,t.fn.alert.Constructor=r,t.fn.alert.noConflict=function(){return t.fn.alert=o,this},t(document).on("click.bs.alert.data-api",e,r.prototype.close)}(jQuery),function(){$(function(){var t;return t=function(t){var n,e,r;for(r=t.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/),delete r[0],e=1;3>=e;)r[e]=parseInt(r[e]).toString(16),1===r[e].length&&(r[e]="0"+r[e]),++e;return n="#"+r.join(""),n.toUpperCase()},$(".swatch").on("mouseenter",function(){var n;return n=t($(this).css("background-color")),$(this).append("<span style='display:none;'>"+n+"</span>"),$(this).find("span").slideDown("fast")}).on("mouseleave",function(){return $(this).find("span").slideUp("fast",function(){return $(this).remove()})}),$("p.lead").hover(function(){return $(this).next().slideDown("fast")},function(){return $(this).next().slideUp("fast")})})}.call(this);